# action.yml
name: 'Upload Release'
description: 'Greet someone and record the time'
inputs:
  github_token:
    required: false
    default: ''
  to_url:
    description: 'The URL that will be accessed to receive the file'
    required: true
    default: ''  
  url_params:
    description: 'URL params'
    required: false
    default: ''
  tag_version:
    description: 'The tag version just released'
    required: false    
  file_param:  # id of input
    description: 'The URL param that used to send the file'
    required: false
    default: 'tag_file'
outputs:
  response:
    description: 'Response from the url'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.to_url }}
    - ${{ inputs.tag_version }}
    - ${{ inputs.file_param }}